In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns

In [10]:
df = pd.read_csv("train.csv")[["Age", "Pclass", "SibSp", "Parch", "Survived"]]
df["Age"] = df["Age"].fillna(df["Age"].mean())

df.isnull().sum()

Age         0
Pclass      0
SibSp       0
Parch       0
Survived    0
dtype: int64

In [11]:
X = df.iloc[:, 0:4]
y = df.iloc[:, -1]

In [12]:
# Train/Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

In [13]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring="accuracy", cv=20))

np.float64(0.6972222222222222)

---

## Applying Feature Engineering

In [ ]:
X["Family_size"] = X["SibSp"] + X["Parch"] + 1
X.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [ ]:
def family_size(x):
    if x == 1:
        return 0  # alone
    elif x > 1 and x <= 4:
        return 1  # small family
    else:
        return 2  # large family

In [18]:
X["Family_type"] = X["Family_size"].apply(family_size)
X.head()

    Age  Pclass  SibSp  Parch  Family_size  Family_type
0  22.0       3      1      0            0            2
1  38.0       1      1      0            0            2
2  26.0       3      0      0            2            1
3  35.0       1      1      0            0            2
4  35.0       3      0      0            2            1

In [ ]:
X.drop(columns=["SibSp", "Parch", "Family_size"], inplace=True)
X.head()

    Age  Pclass  Family_type
0  22.0       3            2
1  38.0       1            2
2  26.0       3            1
3  35.0       1            2
4  35.0       3            1

In [20]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring="accuracy", cv=20))

np.float64(0.7276767676767676)

---

## Feature Splitting