#### Transformers API sklearn
- The fit method is used to learn the parameters from the training data, and the
transform method uses those parameters to transform the data. Any data array that is to be trans-
formed needs to have the same number of features as the data array that was used to fit the model.

In [ ]:
import pandas as pd

df = pd.DataFrame(
    [
        ["green", "M", 10.1, "class2"],
        ["red", "L", 13.5, "class1"],
        ["blue", "XL", 15.3, "class2"],
    ]
)

df.columns = ["color", "size", "price", "classlabel"]
df

   color size  price classlabel
0  green    M   10.1     class2
1    red    L   13.5     class1
2   blue   XL   15.3     class2

In [ ]:
size_mapping = {"XL": 3, "L": 2, "M": 1}

df["size"] = df["size"].map(size_mapping)
df

   color  size  price classlabel
0  green     1   10.1     class2
1    red     2   13.5     class1
2   blue     3   15.3     class2

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

X = df[:].values
color_ohe = OneHotEncoder(categories="auto", drop="first")
color_ohe.fit_transform(X[:, 0].reshape(-1, 1)).toarray()

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [11]:
trf = ColumnTransformer([("ohe", color_ohe, [0]), ("nothing", "passthrough", [1, 2])])
trf.fit_transform(X).astype(float)

array([[ 1. ,  0. ,  1. , 10.1],
       [ 0. ,  1. ,  2. , 13.5],
       [ 0. ,  0. ,  3. , 15.3]])